### ISSUE TITLE
ImportError: cannot import name version after installing pytest-ansible-playbook-runner

### ISSUE THREAD

**Issue by richapandey0009** [final-israel/pytest-ansible-playbook-runner#1]
Did below steps:
1. pip install pytest
2. pip install pytest-ansible
3. pip install pytest-ansible-playbook-runner.

After this, run any pytest command, and that will throw an error  as - "ImportError: cannot import name version"

Example:
command: pytest --version

Error:
pytest --version
Traceback (most recent call last):
  File "/usr/bin/pytest", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/_pytest/config/__init__.py", line 63, in main
    config = _prepareconfig(args, plugins)
  File "/usr/lib/python2.7/site-packages/_pytest/config/__init__.py", line 207, in _prepareconfig
    pluginmanager=pluginmanager, args=args
  File "/usr/lib/python2.7/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/lib/python2.7/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/lib/python2.7/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/lib/python2.7/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/usr/lib/python2.7/site-packages/_pytest/helpconfig.py", line 94, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/usr/lib/python2.7/site-packages/pluggy/callers.py", line 81, in get_result
    _reraise(*ex)  # noqa
  File "/usr/lib/python2.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/lib/python2.7/site-packages/_pytest/config/__init__.py", line 687, in pytest_cmdline_parse
    self.parse(args)
  File "/usr/lib/python2.7/site-packages/_pytest/config/__init__.py", line 895, in parse
    self._preparse(args, addopts=addopts)
  File "/usr/lib/python2.7/site-packages/_pytest/config/__init__.py", line 841, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/usr/lib/python2.7/site-packages/pluggy/manager.py", line 299, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/usr/lib/python2.7/site-packages/importlib_metadata/__init__.py", line 94, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/python2.7/site-packages/_pytest/assertion/rewrite.py", line 304, in load_module
    exec(co, mod.__dict__)
  File "/usr/lib/python2.7/site-packages/pytest_ansible_playbook.py", line 25, in <module>
    from playbook_runner import playbook_runner
  File "/tmp/pip-install-ScbxvP/playbook-runner/playbook_runner/__init__.py", line 1, in <module>
ImportError: cannot import name version

**Comment by richapandey0009** [comment]
Forgot to add python version. Using python 2.7 and pytest 4.6.7 and pytest-ansible-playbook-runner version 0.0.2
